# Generated by Django 2.2.19 on 2023-02-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Group',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.
                                    CASCADE, to='posts.Group'),
        ),
    ]
